# -*- coding: utf-8 -*-
"""Генерирует app/src/main/assets/medicines_catalog.json — справочник препаратов для локального поиска."""
import json
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "assets", "medicines_catalog.json")

# (name_ru, name_lat, klass, [doses...], aliases)
BASE = [
    ("Парацетамол", "Paracetamol", "paracetamol", ["325 мг", "500 мг", "750 мг", "1 г"], "панадол;эффералган;тифлу"),
    ("Ибупрофен", "Ibuprofen", "nsaid", ["200 мг", "400 мг", "600 мг"], "нурофен;миг;адвил"),
    ("Кетопрофен", "Ketoprofen", "nsaid", ["50 мг", "100 мг"], "кетонал;фламакс"),
    ("Диклофенак", "Diclofenac", "nsaid", ["25 мг", "50 мг", "75 мг", "100 мг"], "вольтарен;ортофен"),
    ("Напроксен", "Naproxen", "nsaid", ["250 мг", "500 мг"], "напроксен"),
    ("Мелоксикам", "Meloxicam", "nsaid", ["7,5 мг", "15 мг"], "мовалис;амелотекс"),
    ("Целекоксиб", "Celecoxib", "nsaid", ["100 мг", "200 мг"], "целебрекс"),
    ("Ацетилсалициловая кислота", "Acetylsalicylic acid", "aspirin", ["75 мг", "100 мг", "500 мг"], "аспирин;тромбо асс"),
    ("Метформин", "Metformin", "metformin", ["500 мг", "850 мг", "1000 мг"], "сиофор;глюкофаж"),
    ("Глибенкламид", "Glibenclamide", "sulfonylurea", ["2,5 мг", "5 мг"], "манинил"),
    ("Гликлазид", "Gliclazide", "sulfonylurea", ["30 мг", "60 мг"], "диамикрон"),
    ("Глимепирид", "Glimepiride", "sulfonylurea", ["1 мг", "2 мг", "4 мг"], "амарил"),
    ("Инсулин гларгин", "Insulin glargine", "insulin", ["100 ЕД/мл"], "лантус;туджeo"),
    ("Инсулин аспарт", "Insulin aspart", "insulin", ["100 ЕД/мл"], "новорапид;фиасп"),
    ("Инсулин деглудек", "Insulin degludec", "insulin", ["100 ЕД/мл"], "тресиба"),
    ("Инсулин лизпро", "Insulin lispro", "insulin", ["100 ЕД/мл"], "хумалог"),
    ("Амоксициллин", "Amoxicillin", "antibiotic_pen", ["250 мг", "500 мг", "875 мг"], "оспамокс;флемоксин"),
    ("Амоксициллин + клавулановая кислота", "Amoxicillin+clavulanate", "antibiotic_pen", ["375 мг", "625 мг", "1000 мг"], "аугментин"),
    ("Азитромицин", "Azithromycin", "antibiotic_macrolide", ["250 мг", "500 мг"], "сумамед;зитрокс"),
    ("Кларитромицин", "Clarithromycin", "antibiotic_macrolide", ["250 мг", "500 мг"], "клацид"),
    ("Рокситромицин", "Roxithromycin", "antibiotic_macrolide", ["150 мг", "300 мг"], "рулид"),
    ("Цефалексин", "Cephalexin", "antibiotic_ceph", ["250 мг", "500 мг"], "цефлексин"),
    ("Цефтриаксон", "Ceftriaxone", "antibiotic_ceph", ["1 г"], "цефтриаксон"),
    ("Цефуроксим", "Cefuroxime", "antibiotic_ceph", ["250 мг", "500 мг"], "зиннат"),
    ("Ципрофлоксацин", "Ciprofloxacin", "antibiotic_fq", ["250 мг", "500 мг", "750 мг"], "ципролет"),
    ("Левофлоксацин", "Levofloxacin", "antibiotic_fq", ["250 мг", "500 мг"], "таваник"),
    ("Моксифлоксацин", "Moxifloxacin", "antibiotic_fq", ["400 мг"], "авелокс"),
    ("Доксициклин", "Doxycycline", "antibiotic_tet", ["100 мг"], "доксициклин"),
    ("Флуконазол", "Fluconazole", "antifungal", ["50 мг", "150 мг"], "дифлюкан"),
    ("Омепразол", "Omeprazole", "ppi", ["10 мг", "20 мг", "40 мг"], "озек"),
    ("Эзомепразол", "Esomeprazole", "ppi", ["20 мг", "40 мг"], "нексиум"),
    ("Пантопразол", "Pantoprazole", "ppi", ["20 мг", "40 мг"], "санпраз"),
    ("Ранитидин", "Ranitidine", "h2", ["150 мг", "300 мг"], "ранитидин"),
    ("Фамотидин", "Famotidine", "h2", ["20 мг", "40 мг"], "квамател"),
    ("Лоратадин", "Loratadine", "antihistamine_2nd", ["10 мг"], "кларитин"),
    ("Цетиризин", "Cetirizine", "antihistamine_2nd", ["10 мг"], "зиртек"),
    ("Фексофенадин", "Fexofenadine", "antihistamine_2nd", ["120 мг", "180 мг"], "телфаст"),
    ("Димедрол", "Diphenhydramine", "antihistamine_1st", ["50 мг"], "димедрол"),
    ("Супрастин", "Chloropyramine", "antihistamine_1st", ["25 мг"], "хлоропирамин"),
    ("Дротаверин", "Drotaverine", "spasmolytic", ["40 мг", "80 мг"], "но-шпа"),
    ("Папаверин", "Papaverine", "spasmolytic", ["20 мг", "40 мг"], "папаверин"),
    ("Мебеверин", "Mebeverine", "spasmolytic", ["135 мг", "200 мг"], "дюспаталин"),
    ("Бисопролол", "Bisoprolol", "beta_blocker", ["2,5 мг", "5 мг", "10 мг"], "конкор"),
    ("Метопролол", "Metoprolol", "beta_blocker", ["25 мг", "50 мг", "100 мг"], "беталок"),
    ("Атенолол", "Atenolol", "beta_blocker", ["25 мг", "50 мг", "100 мг"], "атенолол"),
    ("Карведилол", "Carvedilol", "beta_blocker", ["3,125 мг", "6,25 мг", "12,5 мг", "25 мг"], "дилatrend"),
    ("Эналаприл", "Enalapril", "acei", ["2,5 мг", "5 мг", "10 мг", "20 мг"], "энап"),
    ("Лизиноприл", "Lisinopril", "acei", ["5 мг", "10 мг", "20 мг"], "диротон"),
    ("Периндоприл", "Perindopril", "acei", ["2 мг", "4 мг", "8 мг"], "престариум"),
    ("Лозартан", "Losartan", "arb", ["25 мг", "50 мг", "100 мг"], "лозап"),
    ("Валсартан", "Valsartan", "arb", ["40 мг", "80 мг", "160 мг"], "диован"),
    ("Кандесартан", "Candesartan", "arb", ["4 мг", "8 мг", "16 мг", "32 мг"], "атаканд"),
    ("Амлодипин", "Amlodipine", "ccb_dihydro", ["2,5 мг", "5 мг", "10 мг"], "норваск"),
    ("Лерканидипин", "Lercanidipine", "ccb_dihydro", ["10 мг", "20 мг"], "занидип"),
    ("Гидрохлоротиазид", "Hydrochlorothiazide", "diuretic_thiazide", ["12,5 мг", "25 мг"], "гидра"),
    ("Индапамид", "Indapamide", "diuretic_thiazide", ["2,5 мг"], "арифон"),
    ("Фуросемид", "Furosemide", "furosemide", ["20 мг", "40 мг"], "ласикс"),
    ("Спиронолактон", "Spironolactone", "diuretic_thiazide", ["25 мг", "50 мг", "100 мг"], "верошпирон"),
    ("Аторвастатин", "Atorvastatin", "statin", ["10 мг", "20 мг", "40 мг", "80 мг"], "липримар"),
    ("Розувастатин", "Rosuvastatin", "statin", ["5 мг", "10 мг", "20 мг"], "крестор"),
    ("Симвастатин", "Simvastatin", "statin", ["10 мг", "20 мг", "40 мг"], "зокор"),
    ("Клопидогрел", "Clopidogrel", "antiplatelet", ["75 мг"], "плавикс"),
    ("Тикагрелор", "Ticagrelor", "antiplatelet", ["90 мг"], "брелинта"),
    ("Варфарин", "Warfarin", "anticoag_warfarin", ["2,5 мг", "3 мг", "5 мг"], "варфарин"),
    ("Апиксабан", "Apixaban", "anticoag_noac", ["2,5 мг", "5 мг"], "элиquis"),
    ("Ривароксабан", "Rivaroxaban", "anticoag_noac", ["10 мг", "15 мг", "20 мг"], "ксарелто"),
    ("Дабигатран", "Dabigatran", "anticoag_noac", ["110 мг", "150 мг"], "прадакса"),
    ("Нитроглицерин", "Nitroglycerin", "nitrate", ["0,5 мг"], "нитроглицерин"),
    ("Изосорбида динитрат", "Isosorbide dinitrate", "nitrate", ["10 мг", "20 мг"], "изокет"),
    ("Дигоксин", "Digoxin", "digoxin_class", ["0,25 мг"], "дигоксин"),
    ("Левотироксин", "Levothyroxine", "thyroid", ["25 мкг", "50 мкг", "75 мкг", "100 мкг"], "эутирокс"),
    ("Преднизолон", "Prednisolone", "corticosteroid_systemic", ["5 мг", "10 мг", "20 мг"], "преднизолон"),
    ("Дексаметазон", "Dexamethasone", "corticosteroid_systemic", ["0,5 мг", "4 мг"], "дексаметазон"),
    ("Сертралин", "Sertraline", "ssri", ["50 мг", "100 мг"], "золофт"),
    ("Эсциталопрам", "Escitalopram", "ssri", ["5 мг", "10 мг", "20 мг"], "ципралекс"),
    ("Флуоксетин", "Fluoxetine", "ssri", ["20 мг"], "прозак"),
    ("Диазепам", "Diazepam", "benzodiazepine", ["5 мг", "10 мг"], "седуксен"),
    ("Алпразолам", "Alprazolam", "benzodiazepine", ["0,25 мг", "0,5 мг", "1 мг"], "ксанакс"),
    ("Омепразол + домперидон", "Omeprazole+domperidone", "combo_cold", ["комбо"], "осталор"),
    ("Амброксол", "Ambroxol", "mucolytic", ["15 мг", "30 мг"], "лазолван"),
    ("Ацетилцистеин", "Acetylcysteine", "mucolytic", ["200 мг", "600 мг"], "флуимуцил"),
    ("Бромгексин", "Bromhexine", "mucolytic", ["4 мг", "8 мг"], "бромгексин"),
    ("Кодеин", "Codeine", "opioid_codeine", ["10 мг", "15 мг"], "кодеин"),
    ("Аскорбиновая кислота", "Ascorbic acid", "vitamin", ["50 мг", "100 мг", "500 мг", "1000 мг"], "витамин с"),
    ("Витамин D3", "Cholecalciferol", "vitamin", ["400 МЕ", "1000 МЕ", "2000 МЕ"], "аквадетрим"),
    ("Цианокобаламин", "Cyanocobalamin", "vitamin", ["мкг"], "витамин b12"),
    ("Фолиевая кислота", "Folic acid", "vitamin", ["400 мкг", "5 мг"], "фолиевая"),
    ("Железа сульфат", "Ferrous sulfate", "mineral", ["40 мг Fe", "80 мг Fe"], "сорбифер"),
    ("Магния сульфат", "Magnesium sulfate", "mineral", ["25%"], "магнезия"),
    ("Цинка сульфат", "Zinc sulfate", "mineral", ["10 мг"], "цинк"),
    ("Искусственная слеза", "Artificial tears", "eye_tear", ["увлажняющие"], "хилозар"),
    ("Морская соль (назальная)", "Sea salt nasal", "nasal_saline", ["0,9%"], "аквалор"),
    ("Алюминия гидроксид + магния гидроксид", "Al+Mg hydroxide", "antacid", ["комбинированные"], "маалокс"),
    ("Омепразол (OTC)", "Omeprazole", "ppi", ["10 мг"], "озек"),
    ("Валериана", "Valeriana", "herb_sedative", ["экстракт"], "валериана"),
    ("Пустырник", "Leonurus", "herb_sedative", ["настойка"], "пустырник"),
    ("Корвалол", "Corvalol", "cardio_corvalol_like", ["капли"], "корвалол"),
    ("Валидол", "Validol", "general_otc", ["15 мг"], "валидол"),
    ("Нитроглицерин спрей", "Nitroglycerin spray", "nitrate", ["0,4 мг/доза"], "нитроглицерин"),
    ("Осельтамивир", "Oseltamivir", "antiviral_grip", ["75 мг"], "тамифлю"),
    ("Занамивир", "Zanamivir", "antiviral_grip", ["5 мг"], "реленза"),
    ("Ацикловир", "Aciclovir", "antiviral_hep", ["200 мг", "400 мг", "800 мг"], "ацикловир"),
    ("Метронидазол", "Metronidazole", "metronidazole", ["250 мг", "500 мг"], "трихопол"),
    ("Тинидазол", "Tinidazole", "tinidazole", ["500 мг"], "тинидазол"),
    ("Клотримазол", "Clotrimazole", "antifungal_topical", ["1%"], "канестен"),
    ("Миконазол", "Miconazole", "antifungal_topical", ["2%"], "дактарин"),
    ("Гидрокортизон", "Hydrocortisone", "corticosteroid_topical", ["0,5%", "1%"], "гидрокортизон"),
    ("Мометазон", "Mometasone", "corticosteroid_topical", ["0,1%"], "эладон"),
    ("Псевдоэфедрин", "Pseudoephedrine", "decongestant", ["60 мг"], "судофед"),
    ("Ксилометазолин", "Xylometazoline", "decongestant", ["0,05%", "0,1%"], "ксилен"),
    ("Оксиметазолин", "Oxymetazoline", "decongestant", ["0,05%"], "називин"),
    ("Бутамират", "Butamirate", "cough_antitussive", ["50 мг"], "синекод"),
    ("Глауцин", "Glaucine", "cough_antitussive", ["20 мг"], "глауцин"),
    ("Лактулоза", "Lactulose", "lax_osmotic", ["сироп"], "дюфалак"),
    ("Макрогол", "Macrogol", "lax_osmotic", ["саше"], "форлакс"),
    ("Бисакодил", "Bisacodyl", "lax_stimulant", ["5 мг"], "дульколакс"),
    ("Лактобактерии", "Lactobacillus", "probiotic", ["капсулы"], "линекс"),
    ("Бифидобактерии", "Bifidobacterium", "probiotic", ["саше"], "бифиформ"),
    ("Омега-3", "Omega-3", "vitamin", ["1000 мг"], "омакор"),
    ("Мелатонин", "Melatonin", "general_otc", ["3 мг", "5 мг"], "мелатонин"),
    ("Силденафил", "Sildenafil", "sildenafil", ["25 мг", "50 мг", "100 мг"], "виагра"),
    ("Тадалафил", "Tadalafil", "sildenafil", ["5 мг", "20 мг"], "сиалис"),
    ("Тамсулозин", "Tamsulosin", "tamsulosin", ["0,4 мг"], "омник"),
    ("Финастерид", "Finasteride", "finasteride", ["5 мг"], "простам"),
    ("Аллопуринол", "Allopurinol", "allopurinol", ["100 мг", "300 мг"], "аллопуринол"),
    ("Колхицин", "Colchicine", "colchicine", ["0,5 мг"], "колхицин"),
    ("Амиодарон", "Amiodarone", "amiodarone", ["200 мг"], "кордарон"),
    ("Верапамил", "Verapamil", "ccb_benz", ["40 мг", "80 мг", "120 мг"], "изоптин"),
    ("Дилтиазем", "Diltiazem", "ccb_benz", ["60 мг", "90 мг"], "дилтиазем"),
    ("Спиронолактон + гидрохлоротиазид", "Spironolactone+HCTZ", "diuretic_thiazide", ["комбо"], "альдактон"),
    ("Глимепирид + метформин", "Glimepiride+metformin", "metformin", ["комбо"], "амaryl м"),
    ("Ситаглиптин", "Sitagliptin", "dpp4i", ["25 мг", "50 мг", "100 мг"], "янувия"),
    ("Вилдаглиптин", "Vildagliptin", "dpp4i", ["50 мг"], "галвус"),
    ("Лираглутид", "Liraglutide", "glp1", ["6 мг/мл"], "виктоза"),
    ("Семаглутид", "Semaglutide", "glp1", ["1 мг"], "оземпик"),
    ("Дапаглифлозин", "Dapagliflozin", "sglt2", ["5 мг", "10 мг"], "форсига"),
    ("Эмпаглифлозин", "Empagliflozin", "sglt2", ["10 мг", "25 мг"], "джардинс"),
    ("Канаглифлозин", "Canagliflozin", "sglt2", ["100 мг", "300 мг"], "инвокана"),
    ("Левофлоксацин капли", "Levofloxacin drops", "antibiotic_fq", ["0,5%"], "левофлоксацин"),
    ("Тобрамицин", "Tobramycin", "antibiotic_ceph", ["0,3%"], "тобрекс"),
    ("Фузидиевая кислота", "Fusidic acid", "antifungal_topical", ["2%"], "фузидин"),
    ("Урсодезоксихолевая кислота", "Ursodeoxycholic acid", "general_otc", ["250 мг", "500 мг"], "урсосан"),
    ("Месалазин", "Mesalazine", "general_otc", ["500 мг"], "пентаса"),
    ("Сульфасалазин", "Sulfasalazine", "general_otc", ["500 мг"], "сальфалазин"),
    ("Метотрексат", "Methotrexate", "general_otc", ["2,5 мг", "10 мг"], "метотрексат"),
    ("Азатиоприн", "Azathioprine", "general_otc", ["50 мг"], "имуран"),
    ("Микофенолата мофетил", "Mycophenolate mofetil", "general_otc", ["500 мг"], "селлсепт"),
    ("Циклоспорин", "Ciclosporin", "general_otc", ["25 мг", "50 мг", "100 мг"], "сандиммун"),
    ("Такролимус", "Tacrolimus", "general_otc", ["0,5 мг", "1 мг", "5 мг"], "програф"),
    ("Ритуксимаб", "Rituximab", "general_otc", ["концентрат"], "мабтера"),
    ("Инфликсимаб", "Infliximab", "general_otc", ["100 мг"], "ремифорт"),
    ("Адалимумаб", "Adalimumab", "general_otc", ["40 мг"], "хумира"),
    ("Этанерцепт", "Etanercept", "general_otc", ["25 мг", "50 мг"], "энбрел"),
    ("Трастузумаб", "Trastuzumab", "general_otc", ["440 мг"], "герцептин"),
    ("Бевацизумаб", "Bevacizumab", "general_otc", ["400 мг"], "авастин"),
    ("Пембролизумаб", "Pembrolizumab", "general_otc", ["100 мг"], "ключтруда"),
    ("Ниволумаб", "Nivolumab", "general_otc", ["40 мг", "100 мг"], "опдиво"),
    ("Ипилимумаб", "Ipilimumab", "general_otc", ["50 мг"], "ервой"),
    ("Осимертиниб", "Osimertinib", "general_otc", ["40 мг", "80 мг"], "тагриссо"),
    ("Иматиниб", "Imatinib", "general_otc", ["100 мг", "400 мг"], "гливек"),
    ("Сорафениб", "Sorafenib", "general_otc", ["200 мг"], "нексавар"),
    ("Сунитиниб", "Sunitinib", "general_otc", ["12,5 мг", "25 мг", "50 мг"], "сутент"),
    ("Пазопаниб", "Pazopanib", "general_otc", ["200 мг", "400 мг"], "вотриент"),
    ("Кабозантиниб", "Cabozantinib", "general_otc", ["20 мг", "40 мг", "60 мг"], "кометрик"),
    ("Ленватиниб", "Lenvatinib", "general_otc", ["4 мг", "10 мг"], "ленвима"),
    ("Регорафениб", "Regorafenib", "general_otc", ["40 мг"], "стивага"),
    ("Афатиниб", "Afatinib", "general_otc", ["20 мг", "30 мг", "40 мг"], "жиотриф"),
    ("Эрлотиниб", "Erlotinib", "general_otc", ["25 мг", "100 мг", "150 мг"], "тарцева"),
    ("Гефитиниб", "Gefitinib", "general_otc", ["250 мг"], "иреса"),
    ("Кризотиниб", "Crizotinib", "general_otc", ["200 мг", "250 мг"], "ксалкори"),
    ("Алектиниб", "Alectinib", "general_otc", ["150 мг"], "алесенза"),
    ("Осимертиниб + комбо", "Osimertinib combo", "general_otc", ["комбо"], "тагриссо"),
    ("Пеметрексед", "Pemetrexed", "general_otc", ["500 мг"], "алимта"),
    ("Цисплатин", "Cisplatin", "general_otc", ["10 мг", "50 мг"], "цисплатин"),
    ("Карбоплатин", "Carboplatin", "general_otc", ["150 мг", "450 мг"], "карбоплатин"),
    ("Оксалиплатин", "Oxaliplatin", "general_otc", ["50 мг", "100 мг"], "элоксатин"),
    ("Доцетаксел", "Docetaxel", "general_otc", ["20 мг", "80 мг"], "таксотер"),
    ("Паклитаксел", "Paclitaxel", "general_otc", ["30 мг", "100 мг", "300 мг"], "таксол"),
    ("Винкристин", "Vincristine", "general_otc", ["1 мг"], "онковин"),
    ("Доксорубицин", "Doxorubicin", "general_otc", ["10 мг", "50 мг"], "адриабластин"),
    ("Эпирубицин", "Epirubicin", "general_otc", ["10 мг", "50 мг"], "фарморубицин"),
    ("Циклофосфамид", "Cyclophosphamide", "general_otc", ["50 мг"], "эндоксан"),
    ("Ифосфамид", "Ifosfamide", "general_otc", ["1 г", "2 г"], "ифос"),
    ("Мелфалан", "Melphalan", "general_otc", ["2 мг"], "алкеран"),
    ("Хлорамбуцил", "Chlorambucil", "general_otc", ["2 мг"], "лейкеран"),
    ("Флударабин", "Fludarabine", "general_otc", ["10 мг"], "флудара"),
    ("Кладрибин", "Cladribine", "general_otc", ["10 мг"], "лейстатин"),
    ("Пентостатин", "Pentostatin", "general_otc", ["10 мг"], "нипент"),
    ("Бендамустин", "Bendamustine", "general_otc", ["25 мг", "100 мг"], "треанда"),
    ("Пралатрексат", "Pralatrexate", "general_otc", ["20 мг"], "фолотын"),
    ("Ралтитрексед", "Raltitrexed", "general_otc", ["2 мг"], "томудекс"),
    ("Гемцитабин", "Gemcitabine", "general_otc", ["200 мг", "1 г"], "гемзар"),
    ("Цитарабин", "Cytarabine", "general_otc", ["100 мг", "500 мг"], "цитозар"),
    ("Метотрексат (инъекции)", "Methotrexate inj", "general_otc", ["25 мг/мл"], "метотрексат"),
    ("Меркаптопурин", "Mercaptopurine", "general_otc", ["50 мг"], "пуринетол"),
    ("Тиогуанин", "Tioguanine", "general_otc", ["40 мг"], "ланвис"),
    ("Клорамбуцил (таблетки)", "Chlorambucil tabs", "general_otc", ["2 мг"], "лейкеран"),
    ("Прокарбазин", "Procarbazine", "general_otc", ["50 мг"], "матулан"),
    ("Дакарбазин", "Dacarbazine", "general_otc", ["100 мг", "200 мг"], "дтик"),
    ("Темозоломид", "Temozolomide", "general_otc", ["5 мг", "20 мг", "100 мг", "250 мг"], "темодал"),
    ("Иринотекан", "Irinotecan", "general_otc", ["40 мг/мл"], "камптосар"),
    ("Топотекан", "Topotecan", "general_otc", ["1 мг", "4 мг"], "икамтин"),
    ("Этопозид", "Etoposide", "general_otc", ["50 мг", "100 мг"], "вепезид"),
    ("Тенипозид", "Teniposide", "general_otc", ["50 мг"], "вумон"),
    ("Блеомицин", "Bleomycin", "general_otc", ["15 ед"], "бленоксан"),
    ("Митомицин", "Mitomycin", "general_otc", ["2 мг", "10 мг"], "митомицин"),
    ("Актиномицин D", "Dactinomycin", "general_otc", ["0,5 мг"], "космеген"),
    ("Митоксантрон", "Mitoxantrone", "general_otc", ["2 мг/мл"], "новантрон"),
    ("Идарубицин", "Idarubicin", "general_otc", ["5 мг", "10 мг"], "заведос"),
    ("Даунорубицин", "Daunorubicin", "general_otc", ["20 мг"], "церубидин"),
    ("Митоксантрон (концентрат)", "Mitoxantrone conc", "general_otc", ["2 мг/мл"], "новантрон"),
]

FORMS_ROT = [
    "таблетки",
    "капсулы",
    "таблетки покрытые оболочкой",
    "раствор для приёма внутрь",
    "суспензия",
    "сироп",
    "гранулы",
    "раствор для инъекций",
    "мазь для наружного применения",
    "гель",
    "капли глазные",
    "капли назальные",
    "суппозитории ректальные",
]


def expand():
    rows = []
    for name_ru, name_lat, klass, doses, aliases in BASE:
        for i, dose in enumerate(doses):
            form = FORMS_ROT[(hash(name_ru) + i) % len(FORMS_ROT)]
            rows.append(
                {
                    "name_ru": f"{name_ru} ({dose})" if dose != "комбо" else name_ru,
                    "name_lat": name_lat,
                    "dosage": dose if dose != "комбо" else "комбинированная дозировка по инструкции",
                    "form": form,
                    "klass": klass,
                    "manufacturer": "различные производители",
                    "active_substance": name_lat,
                    "aliases": aliases,
                }
            )
    return rows


def main():
    rows = expand()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(rows, f, ensure_ascii=False, separators=(",", ":"))
    print("written", OUT, "count", len(rows))


if __name__ == "__main__":
    main()
